# Generated by Django 5.2.1 on 2025-11-14 07:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractorBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('block_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('table', 'Table'), ('image', 'Image'), ('heading', 'Heading'), ('instruction', 'Instruction'), ('rubric', 'Rubric')], max_length=20)),
                ('xml', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('w', models.FloatField(blank=True, null=True)),
                ('h', models.FloatField(blank=True, null=True)),
                ('is_qheader', models.BooleanField(default=False)),
                ('detected_qnum', models.CharField(blank=True, max_length=50)),
                ('detected_marks', models.CharField(blank=True, max_length=50)),
                ('rand_order_index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ExtractorPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('module_name', models.CharField(blank=True, default='', max_length=255)),
                ('paper_number', models.CharField(blank=True, default='', max_length=50)),
                ('paper_letter', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractorTestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('module_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('saqa_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegexPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField()),
                ('description', models.TextField()),
                ('match_score', models.FloatField()),
                ('example_usage', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('default', 'Awaiting Activation'), ('admin', 'Administrator'), ('assessor_dev', 'Assessor (Developer)'), ('moderator', 'Moderator (Developer)'), ('qcto', 'QCTO Validator'), ('etqa', 'ETQA'), ('learner', 'Learner'), ('assessor_marker', 'Assessor (Marker)'), ('internal_mod', 'Internal Moderator'), ('external_mod', 'External Moderator (QALA)'), ('assessment_center', 'Assessment Center')], default='learner', max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_number', models.CharField(blank=True, help_text='Unique student number for learners', max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('qualification_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('assessment_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_users', to='core.assessmentcentre')),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.qualification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eisa_id', models.CharField(max_length=50)),
                ('paper', models.CharField(max_length=50)),
                ('paper_type', models.CharField(choices=[('admin_upload', 'Admin Upload'), ('randomized', 'Randomized Paper')], default='admin_upload', max_length=50)),
                ('saqa_id', models.CharField(blank=True, max_length=50, null=True)),
                ('moderator', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='assessments/')),
                ('memo', models.FileField(blank=True, help_text='Memo file for admin-uploaded assessments', null=True, upload_to='assessments/memos/')),
                ('comment', models.TextField(blank=True)),
                ('forward_to_moderator', models.BooleanField(default=False)),
                ('moderator_report', models.FileField(blank=True, help_text='Word document report from moderator', null=True, upload_to='moderator_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qcto_report', models.FileField(blank=True, help_text='Word document report from qcto', null=True, upload_to='qcto_reports/')),
                ('is_selected_by_etqa', models.BooleanField(default=False)),
                ('memo_file', models.FileField(blank=True, help_text='Memo file for randomized assessments requiring ETQA approval', null=True, upload_to='memos/randomized/')),
                ('etqa_approved', models.BooleanField(default=False)),
                ('etqa_comments', models.TextField(blank=True)),
                ('etqa_approved_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_moderation', 'Pending Moderation'), ('moderated', 'Moderated'), ('pending_etqa', 'Pending ETQA Review'), ('etqa_approved', 'ETQA Approved'), ('etqa_rejected', 'ETQA Rejected'), ('pending_qcto', 'Pending QCTO Review'), ('qcto_approved', 'QCTO Approved'), ('qcto_rejected', 'QCTO Rejected'), ('Released to students', 'Released to students'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('status_changed_at', models.DateTimeField(auto_now_add=True)),
                ('module_name', models.CharField(default='Unknown Module', help_text='e.g. Chemical Operations', max_length=100)),
                ('module_number', models.CharField(default='1A', help_text='Module identifier (1A, 1B, etc)', max_length=2)),
                ('questions_randomized', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_created', to=settings.AUTH_USER_MODEL)),
                ('status_changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('extractor_paper', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_record', to='core.extractorpaper')),
            ],
            options={
                'permissions': [('can_moderate', 'Can moderate assessments'), ('can_etqa_review', 'Can review as ETQA'), ('can_qcto_review', 'Can review as QCTO')],
            },
        ),
        migrations.CreateModel(
            name='ExtractorBlockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='paper_images/')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.extractorblock')),
            ],
        ),
        migrations.AddField(
            model_name='extractorblock',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.extractorpaper'),
        ),
        migrations.CreateModel(
            name='ExtractorTestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0)),
                ('question_number', models.CharField(blank=True, max_length=50)),
                ('marks', models.CharField(blank=True, max_length=50)),
                ('qtype', models.CharField(blank=True, max_length=50)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.extractortestpaper')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ExtractorUserBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('w', models.FloatField()),
                ('h', models.FloatField()),
                ('order_index', models.IntegerField(default=0)),
                ('question_number', models.CharField(blank=True, max_length=50)),
                ('marks', models.CharField(blank=True, max_length=50)),
                ('qtype', models.CharField(blank=True, max_length=50)),
                ('parent_number', models.CharField(blank=True, max_length=50)),
                ('header_label', models.CharField(blank=True, max_length=255)),
                ('case_study_label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_boxes', to='core.extractorpaper')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Revised', 'Revised'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('marks', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='core.assessment')),
                ('case_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.casestudy')),
            ],
        ),
        migrations.CreateModel(
            name='OfflineStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_students_created', to=settings.AUTH_USER_MODEL)),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qualification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_randomized', models.BooleanField(default=False)),
                ('structure_json', models.JSONField(blank=True, default=dict)),
                ('total_marks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers_created', to=settings.AUTH_USER_MODEL)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('attempt_number', models.IntegerField()),
                ('pdf_file', models.FileField(upload_to='exam_submissions/%Y/%m/%d/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_offline', models.BooleanField(default=False)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('marked_paper', models.FileField(blank=True, null=True, upload_to='marked_papers/marker/%Y/%m/%d/')),
                ('internal_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('internal_total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('internal_graded_at', models.DateTimeField(blank=True, null=True)),
                ('internal_feedback', models.TextField(blank=True)),
                ('internal_marked_paper', models.FileField(blank=True, null=True, upload_to='marked_papers/internal/%Y/%m/%d/')),
                ('external_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('external_total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('external_graded_at', models.DateTimeField(blank=True, null=True)),
                ('external_feedback', models.TextField(blank=True)),
                ('external_marked_paper', models.FileField(blank=True, null=True, upload_to='marked_papers/external/%Y/%m/%d/')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assessment')),
                ('external_graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('internal_graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offline_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.offlinestudent')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paper')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='paper_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='core.paper'),
        ),
        migrations.CreateModel(
            name='PaperBankEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='paper_bank/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper_bank_entry', to='core.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('submitted_to_center', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assessment')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assessmentcentre')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.qualification')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentcentre',
            name='qualification_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qualification'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qualification'),
        ),
        migrations.CreateModel(
            name='QuestionBankEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('standard', 'Standard'), ('case_study', 'Case Study'), ('mcq', 'Multiple Choice')], default='standard', max_length=20)),
                ('text', models.TextField()),
                ('marks', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.casestudy')),
                ('qualification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(limit_choices_to={'question_type': 'mcq'}, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.questionbankentry')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('content_html', models.TextField(blank=True, help_text='Paste question text, tables, images (HTML) here.')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questionbankentry')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('assessment', 'question')},
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(related_name='assessments', through='core.AssessmentQuestion', to='core.questionbankentry'),
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.generatedquestion')),
            ],
            options={
                'verbose_name': 'Exam Answer',
                'verbose_name_plural': 'Exam Answers',
                'unique_together': {('user', 'question', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='ExamNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('question', 'Question'), ('table', 'Table'), ('image', 'Image'), ('text', 'Text'), ('instruction', 'Instruction')], max_length=20)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('marks', models.CharField(blank=True, max_length=10, null=True)),
                ('content', models.JSONField(blank=True, default=list)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.examnode')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.paper')),
            ],
            options={
                'ordering': ['order_index'],
                'indexes': [models.Index(fields=['paper', 'node_type'], name='core_examno_paper_i_3b1059_idx'), models.Index(fields=['paper', 'number'], name='core_examno_paper_i_686969_idx')],
            },
        ),
    ]
